# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SVM_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('fl_smoking', models.IntegerField(choices=[(1, '1'), (3, '3')], default=1)),
                ('fl_nonveg', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=1)),
                ('OccupationType', models.IntegerField(choices=[(9, '9'), (10, '10'), (15, '15')], default=9)),
            ],
        ),
    ]
