# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20170604_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='svm_model',
            name='FI_FDiagnosis',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
