# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20170604_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='svm_model',
            name='HGB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='svm_model',
            name='WBCLAB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
