# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20170604_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svm_model',
            name='Age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='svm_model',
            name='FI_FDiagnosis',
            field=models.CharField(default=0, editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='svm_model',
            name='Nonveg',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='svm_model',
            name='OccupationType',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('15', '15')], default='9', max_length=5),
        ),
        migrations.AlterField(
            model_name='svm_model',
            name='Smoking',
            field=models.CharField(choices=[('1', '1'), ('3', '3')], default='1', max_length=5),
        ),
    ]
